### ISSUE TITLE
a new error in play time goals in 2.1.5BETA

### ISSUE THREAD

**Issue by BallkingCN** [CoolDCB/ActivityRewarder#10]
https://smrt-1.com/pastes/rGfQ4f1

it means all of daily play-time goals reward will be given in the first goal

i dont change my config

**Comment by CoolDCB** [comment]
All of the rewards get given from the start? That's really odd, apologies for all these issues.

**Comment by CoolDCB** [comment]
I've changed the data storage for the Daily Playtimes Module to fix this issue! Let me know if you have any more issues, sorry again for all the errors with this feature!
[ActivityRewarder-2.1.5-BETA.zip](https://github.com/CoolDCB/ActivityRewarder/files/13167653/ActivityRewarder-2.1.5-BETA.zip)

**Comment by BallkingCN** [comment]
> I've changed the data storage for the Daily Playtimes Module to fix this issue! Let me know if you have any more issues, sorry again for all the errors with this feature! [ActivityRewarder-2.1.5-BETA.zip](https://github.com/CoolDCB/ActivityRewarder/files/13167653/ActivityRewarder-2.1.5-BETA.zip)

u r hero for all server owner used folia.

thanks for ur all work for the plugin

it is the only plugin can reward player in folia

**Comment by CoolDCB** [comment]
I'm glad I can help :)
