### ISSUE TITLE
[ADD]: Create a README.md

### ISSUE THREAD

**Issue by Jacinth-Mahanta** [CoolDCB/ActivityRewarder#11]
The repo is missing a README.md file. I want to work on the README file as a part of the Modtoberfest. Kindly assign this issue to me.

**Comment by CoolDCB** [comment]
There you go!

**Comment by Jacinth-Mahanta** [comment]
Will be submitting the PR by today itself....

**Comment by Jacinth-Mahanta** [comment]
PR proposed!

**Comment by CoolDCB** [comment]
Thank you for the PR! Appreciate you :)

**Comment by Jacinth-Mahanta** [comment]
Kindly add the Modtober tags.
