### ISSUE TITLE
Playtime Rewards not Functioning

### ISSUE THREAD

**Issue by BallkingCN** [CoolDCB/ActivityRewarder#5]
it dnothing

**Comment by CoolDCB** [comment]
It does nothing? Are there any errors, does the plugin load? I'll try and test this on my test server nonetheless

**Comment by CoolDCB** [comment]
Oops

**Comment by BallkingCN** [comment]
> Oops, apologies that was a misclick

the onlinereward cant be used

**Comment by CoolDCB** [comment]
Online reward?

**Comment by BallkingCN** [comment]
> Online reward?

yes,it doesnt work since yesterday or 3 days ago

**Comment by CoolDCB** [comment]
What do you mean by an online reward?

**Comment by BallkingCN** [comment]
daily-playtime-goals.yml

**Comment by CoolDCB** [comment]
Gotcha, thank you

**Comment by CoolDCB** [comment]
Is this the only thing not working on Folia?

**Comment by BallkingCN** [comment]
> Is this the only thing not working on Folia?

maybe?i dont find other error

thanks for ur selfless help make me can use it on folia

**Comment by Kongchenglige** [comment]
Hi, CoolDCB

Sorry for using opening an issue way to request support.

I'm tech support on his server and let me supply more information about our situation.

We are running ActivityRewarder v2.1.3 on our [Kaiiju(a folia fork)](https://github.com/KaiijuMC/Kaiiju) server.


> It does nothing? Are there any errors, does the plugin load? I'll try and test this on my test server nonetheless

No, other functions like daily-rewards can work fine.
No, there is no error when I reload the plugin.

We set the refresh-time value in the daily-playtime-goals.yml to 1 and I'm sure the daily-playtime-goals value in the config.yml has been set to true.

The daily-playtime-goals 's problem seems like, it's always setting the value of the last-collected-playtime on 0(I tried to edit it manually and reload the plugin) and never adding up.
```
daily-playtime-goals:
  last-collected-playtime: 0
```

If you need more information to deal with this problem, just tell me.

Thanks for you selfless help!

Here are the logs when I try to reload. (in this case, I try to get daily-rewards)
```

[10:59:22 INFO]: Sorano_machi issued server command: /rewards reload
[10:59:22 INFO]: [ActivityRewarder] Successfully loaded 6 reward collections from 'daily-rewards'
[10:59:22 INFO]: [ActivityRewarder] Successfully loaded 7 reward collections from 'daily-goals'
[10:59:23 INFO]: [ActivityRewarder] Loaded item-template: default-reward
[10:59:23 INFO]: [ActivityRewarder] Loaded item-template: redeemable-reward
[10:59:23 INFO]: [ActivityRewarder] Loaded item-template: collected-reward
[10:59:23 INFO]: [ActivityRewarder] Loaded item-template: missed-reward
[10:59:23 INFO]: [ActivityRewarder] Loaded item-template: upcoming-reward
[10:59:23 INFO]: [ActivityRewarder] Loaded item-template: #
[10:59:23 INFO]: [ActivityRewarder] Loaded item-template: P
[10:59:25 INFO]: Sorano_machi issued server command: /rewards
[10:59:30 INFO]: Sorano_machi issued server command: /rewards claim
[10:59:30 INFO]: [Essentials] CONSOLE issued server command: /eco give Sorano_machi 5

```

**Comment by CoolDCB** [comment]
This is the perfect place to put this! It's a bug in the plugin itself, I'll have a look into the issue and let you know when I have more information!

**Comment by CoolDCB** [comment]
This version should resolve this issue, let me know [ActivityRewarder-2.1.4-BETA.zip](https://github.com/CoolDCB/ActivityRewarder/files/12916072/ActivityRewarder-2.1.4-BETA.zip)

**Comment by CoolDCB** [comment]
Alrighty all should now work: [ActivityRewarder-2.1.4-BETA.zip](https://github.com/CoolDCB/ActivityRewarder/files/12917679/ActivityRewarder-2.1.4-BETA.zip)

**Comment by CoolDCB** [comment]
Last collected playtime will only update when you collect a reward, are rewards being given to the player?

**Comment by CoolDCB** [comment]
No worries!

I see, do you think you could send me your `daily-playtime-goals.yml` and also the player who's testing's data file

**Comment by CoolDCB** [comment]
The issue should be resolved in this build: [ActivityRewarder-2.1.4-BETA.zip](https://github.com/CoolDCB/ActivityRewarder/files/12919132/ActivityRewarder-2.1.4-BETA.zip)

**Comment by BallkingCN** [comment]
> No worries at all! Glad I could get it working for you

a suggestion,the reward only pay for players when they play,can we make a option to open or close it?
"does not include time that players are idle/afk."

**Comment by BallkingCN** [comment]
thanks for hearing my suggestion,its not a bug

**Comment by CoolDCB** [comment]
I'm sorry I don't quite understand the suggestion, do you think you could make a new issue regarding this feature request
